#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
# except for TCP ports 22, 443 and 80.

# Install ufw
echo -e "Updating\n"

sudo apt-get update

sudo apt-get install ufw

sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

sudo apt-get install -y ufw

echo -e "configuring ufw...\n"

# Enable ufw
sudo ufw disable
sudo ufw enable

# Allow outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Check the status of ufw to verify the rules
sudo ufw status

echo -e "process Completed.\n"
